# for Watermill development purposes.
# For Watermill based application docker please check https://watermill.io/docs/getting-started/

services:

  postgres:
    image: postgres:15.3
    restart: unless-stopped
    command: postgres -c 'max_connections=50000'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: watermill
      POSTGRES_DB: watermill
      POSTGRES_PASSWORD: "password"
